-- Einmal im Supabase SQL Editor ausführen.
-- Danach die UUID des eigenen, nicht-anonymen Auth-Benutzers in app_admins eintragen.

create table if not exists public.app_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.guide_products (
  id bigint generated by default as identity primary key,
  product_key text not null unique,
  title text not null check (char_length(title) between 2 and 120),
  recommendation text not null check (char_length(recommendation) between 2 and 160),
  category text not null check (category in ('nachtloesung', 'reinigung', 'toilette', 'packout', 'sichtschutz')),
  url text not null check (url ~ '^https://'),
  rating_note text not null default 'Bewertungen und Preis vor dem Kauf prüfen',
  enabled boolean not null default true,
  sort_order integer not null default 100,
  updated_at timestamptz not null default now()
);

create index if not exists guide_products_enabled_sort_idx
  on public.guide_products (enabled, sort_order, id);

alter table public.app_admins enable row level security;
alter table public.guide_products enable row level security;

drop policy if exists "Admins read own role" on public.app_admins;
create policy "Admins read own role" on public.app_admins
  for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "Enabled products are public and admins see all" on public.guide_products;
create policy "Enabled products are public and admins see all" on public.guide_products
  for select to anon, authenticated using (
    enabled or exists (
      select 1 from public.app_admins where user_id = (select auth.uid())
    )
  );

drop policy if exists "Admins insert products" on public.guide_products;
create policy "Admins insert products" on public.guide_products
  for insert to authenticated with check (
    exists (select 1 from public.app_admins where user_id = (select auth.uid()))
  );
drop policy if exists "Admins update products" on public.guide_products;
create policy "Admins update products" on public.guide_products
  for update to authenticated
  using (exists (select 1 from public.app_admins where user_id = (select auth.uid())))
  with check (exists (select 1 from public.app_admins where user_id = (select auth.uid())));
drop policy if exists "Admins delete products" on public.guide_products;
create policy "Admins delete products" on public.guide_products
  for delete to authenticated
  using (exists (select 1 from public.app_admins where user_id = (select auth.uid())));

grant select on public.app_admins to authenticated;
grant select on public.guide_products to anon, authenticated;
grant insert, update, delete on public.guide_products to authenticated;

insert into public.guide_products
  (product_key, title, recommendation, category, url, rating_note, enabled, sort_order)
values
  ('pibella-travel', 'Pibella Travel', 'Anatomische Urinierhilfe', 'nachtloesung', 'https://pibella.com/', 'Herstellerbeispiel · Eignung zuhause testen', true, 10),
  ('nalgene-wide-mouth', 'Nalgene 1 l Wide Mouth', 'Dicht schließende Weithalsflasche', 'nachtloesung', 'https://nalgene.eu/de/produktkategorie/nach-grose/1l-de/', 'Herstellerbeispiel · ausschließlich markiert als Urinflasche nutzen', true, 20),
  ('traveljohn', 'TravelJohn Einwegurinal', 'Gel-Urinalbeutel für den Notfall', 'nachtloesung', 'https://www.airteam.eu/de/p/traveljohn', 'Etabliertes Produktbeispiel · Preis und Bewertungen prüfen', true, 30),
  ('happypo', 'HappyPo Easy Bidet', 'Reisepo-Dusche', 'reinigung', 'https://www.dm.de/happypo-po-dusche-easy-bidet-p4260487760010.html', 'Erreichbare Händlerseite · Verfügbarkeit und Preis prüfen', true, 40),
  ('cleanwaste', 'Cleanwaste GO Anywhere', 'Falttoilette und Pack-out-System', 'packout', 'https://cleanwaste.com/product/go-anywhere-total-system/', 'Herstellerbeispiel · EU-Verfügbarkeit und Entsorgung prüfen', true, 50),
  ('thetford-335', 'Thetford Porta Potti 335', 'Kompakte Toilette mit Spülung', 'toilette', 'https://www.fritz-berger.de/artikel/thetford-porta-potti-335-tragbare-campingtoilette-116928?varid=69095', '4,9/5 aus 52 verifizierten Händlerbewertungen · Stand 10.08.2026', true, 60),
  ('boxio-toilet', 'BOXIO Toilet', 'Trockentrenntoilette im Euroboxformat', 'toilette', 'https://boxio.de/products/trenntoilette', '242 Produktbewertungen beim Hersteller · Stand 10.08.2026', true, 70),
  ('trelino-evo-s', 'Trelino Evo S', 'Kompakte Trockentrenntoilette', 'toilette', 'https://www.trelino.com/de/products/trelino%C2%AE-evo-s', 'Marke 4,7/5 bei 1.094 Trustpilot-Bewertungen · Stand 10.08.2026', true, 80),
  ('clesana-x1', 'Clesana X1', 'Mobile Verschweißtoilette', 'toilette', 'https://www.shop.clesana.com/products/clesana-x1', 'Premiumbeispiel · Preis, Akku und Verfügbarkeit prüfen', true, 90),
  ('wolfwise-privacy', 'WolfWise Privacy Tent', 'Pop-up-Sichtschutz für Toilette und Dusche', 'sichtschutz', 'https://www.wolfwise.com/products/wolfwise-pop-up-privacy-shower-tent-lp250644bl', 'Herstellerbewertungen vorhanden · Lieferbarkeit in Europa prüfen', true, 100)
on conflict (product_key) do update set
  title = excluded.title,
  recommendation = excluded.recommendation,
  category = excluded.category,
  url = excluded.url,
  rating_note = excluded.rating_note,
  sort_order = excluded.sort_order,
  updated_at = now();

-- Erst nach der Anmeldung in admin.html ausführen und UUID ersetzen:
-- insert into public.app_admins (user_id) values ('DEINE-AUTH-USER-UUID');
