-- Einmal vollständig im Supabase SQL Editor ausführen.

create table if not exists public.app_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.ratings (
  id bigint generated by default as identity primary key,
  spot_id text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  value smallint not null check (value between 1 and 5),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (spot_id, user_id)
);

create table if not exists public.comments (
  id uuid primary key default gen_random_uuid(),
  spot_id text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 1000),
  created_at timestamptz not null default now()
);

create table if not exists public.comment_photos (
  id bigint generated by default as identity primary key,
  comment_id uuid not null references public.comments(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  storage_path text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.spot_verifications (
  id uuid primary key default gen_random_uuid(),
  spot_id text not null,
  user_id uuid references auth.users(id) on delete set null,
  source_type text not null check (source_type in ('own_experience', 'comment', 'instagram', 'other')),
  summary text not null check (char_length(summary) between 20 and 1000),
  visited_on date,
  source_url text check (source_url is null or source_url = '' or source_url ~ '^https://'),
  rights_confirmed boolean not null default false,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create index if not exists ratings_spot_id_idx on public.ratings (spot_id);
create index if not exists comments_spot_id_created_at_idx on public.comments (spot_id, created_at desc);
create index if not exists comment_photos_comment_id_idx on public.comment_photos (comment_id);
create index if not exists spot_verifications_spot_status_idx
  on public.spot_verifications (spot_id, status, created_at desc);

alter table public.ratings enable row level security;
alter table public.comments enable row level security;
alter table public.comment_photos enable row level security;
alter table public.spot_verifications enable row level security;

drop policy if exists "Ratings are public" on public.ratings;
create policy "Ratings are public" on public.ratings
  for select to anon, authenticated using (true);
drop policy if exists "Users create own ratings" on public.ratings;
create policy "Users create own ratings" on public.ratings
  for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists "Users update own ratings" on public.ratings;
create policy "Users update own ratings" on public.ratings
  for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "Comments are public" on public.comments;
create policy "Comments are public" on public.comments
  for select to anon, authenticated using (true);
drop policy if exists "Users create own comments" on public.comments;
create policy "Users create own comments" on public.comments
  for insert to authenticated with check ((select auth.uid()) = user_id);

drop policy if exists "Comment photos are public" on public.comment_photos;
create policy "Comment photos are public" on public.comment_photos
  for select to anon, authenticated using (true);
drop policy if exists "Users create own comment photos" on public.comment_photos;
create policy "Users create own comment photos" on public.comment_photos
  for insert to authenticated with check ((select auth.uid()) = user_id);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'spot-photos',
  'spot-photos',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Spot photos are publicly readable" on storage.objects;
create policy "Spot photos are publicly readable" on storage.objects
  for select to anon, authenticated using (bucket_id = 'spot-photos');
drop policy if exists "Users upload spot photos in own folder" on storage.objects;
create policy "Users upload spot photos in own folder" on storage.objects
  for insert to authenticated with check (
    bucket_id = 'spot-photos'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

drop policy if exists "Approved verifications are public" on public.spot_verifications;
create policy "Approved verifications are public" on public.spot_verifications
  for select to anon, authenticated using (status = 'approved');
drop policy if exists "Users read own verification submissions" on public.spot_verifications;
create policy "Users read own verification submissions" on public.spot_verifications
  for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "Users submit own pending verifications" on public.spot_verifications;
create policy "Users submit own pending verifications" on public.spot_verifications
  for insert to authenticated with check (
    (select auth.uid()) = user_id and status = 'pending'
  );
drop policy if exists "Admins manage verification submissions" on public.spot_verifications;
create policy "Admins manage verification submissions" on public.spot_verifications
  for all to authenticated
  using (exists (select 1 from public.app_admins where user_id = (select auth.uid())))
  with check (exists (select 1 from public.app_admins where user_id = (select auth.uid())));

grant select, insert on public.spot_verifications to authenticated;
grant select on public.spot_verifications to anon;
grant update, delete on public.spot_verifications to authenticated;
