-- Einmal im Supabase SQL Editor ausführen.
-- Danach die UUID des eigenen, nicht-anonymen Auth-Benutzers in app_admins eintragen.

create table if not exists public.app_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.guide_products (
  id bigint generated by default as identity primary key,
  product_key text not null unique,
  title text not null check (char_length(title) between 2 and 120),
  recommendation text not null check (char_length(recommendation) between 2 and 160),
  category text not null check (category in ('nachtloesung', 'reinigung', 'toilette', 'packout', 'sichtschutz')),
  url text not null check (url ~ '^https://'),
  rating_note text not null default 'Bewertungen und Preis vor dem Kauf prüfen',
  enabled boolean not null default true,
  sort_order integer not null default 100,
  updated_at timestamptz not null default now()
);

create table if not exists public.guide_sources (
  id bigint generated by default as identity primary key,
  source_key text not null unique,
  section text not null check (section in ('sanitation', 'media_video', 'media_resource')),
  label text not null check (char_length(label) between 2 and 120),
  title text not null check (char_length(title) between 2 and 160),
  description text not null check (char_length(description) between 2 and 240),
  url text not null check (url ~ '^https://'),
  image_url text check (image_url is null or image_url = '' or image_url ~ '^https://'),
  enabled boolean not null default true,
  sort_order integer not null default 100,
  updated_at timestamptz not null default now()
);

create index if not exists guide_products_enabled_sort_idx
  on public.guide_products (enabled, sort_order, id);
create index if not exists guide_sources_section_enabled_sort_idx
  on public.guide_sources (section, enabled, sort_order, id);

alter table public.app_admins enable row level security;
alter table public.guide_products enable row level security;
alter table public.guide_sources enable row level security;

drop policy if exists "Admins read own role" on public.app_admins;
create policy "Admins read own role" on public.app_admins
  for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "Enabled products are public and admins see all" on public.guide_products;
create policy "Enabled products are public and admins see all" on public.guide_products
  for select to anon, authenticated using (
    enabled or exists (
      select 1 from public.app_admins where user_id = (select auth.uid())
    )
  );

drop policy if exists "Admins insert products" on public.guide_products;
create policy "Admins insert products" on public.guide_products
  for insert to authenticated with check (
    exists (select 1 from public.app_admins where user_id = (select auth.uid()))
  );
drop policy if exists "Admins update products" on public.guide_products;
create policy "Admins update products" on public.guide_products
  for update to authenticated
  using (exists (select 1 from public.app_admins where user_id = (select auth.uid())))
  with check (exists (select 1 from public.app_admins where user_id = (select auth.uid())));
drop policy if exists "Admins delete products" on public.guide_products;
create policy "Admins delete products" on public.guide_products
  for delete to authenticated
  using (exists (select 1 from public.app_admins where user_id = (select auth.uid())));

grant select on public.app_admins to authenticated;
grant select on public.guide_products to anon, authenticated;
grant insert, update, delete on public.guide_products to authenticated;

drop policy if exists "Enabled sources are public and admins see all" on public.guide_sources;
create policy "Enabled sources are public and admins see all" on public.guide_sources
  for select to anon, authenticated using (
    enabled or exists (select 1 from public.app_admins where user_id = (select auth.uid()))
  );
drop policy if exists "Admins insert sources" on public.guide_sources;
create policy "Admins insert sources" on public.guide_sources
  for insert to authenticated with check (
    exists (select 1 from public.app_admins where user_id = (select auth.uid()))
  );
drop policy if exists "Admins update sources" on public.guide_sources;
create policy "Admins update sources" on public.guide_sources
  for update to authenticated
  using (exists (select 1 from public.app_admins where user_id = (select auth.uid())))
  with check (exists (select 1 from public.app_admins where user_id = (select auth.uid())));
drop policy if exists "Admins delete sources" on public.guide_sources;
create policy "Admins delete sources" on public.guide_sources
  for delete to authenticated
  using (exists (select 1 from public.app_admins where user_id = (select auth.uid())));

grant select on public.guide_sources to anon, authenticated;
grant insert, update, delete on public.guide_sources to authenticated;

insert into public.guide_products
  (product_key, title, recommendation, category, url, rating_note, enabled, sort_order)
values
  ('pibella-travel', 'Pibella Travel', 'Anatomische Urinierhilfe', 'nachtloesung', 'https://pibella.com/', 'Herstellerbeispiel · Eignung zuhause testen', true, 10),
  ('nalgene-wide-mouth', 'Nalgene 1 l Wide Mouth', 'Dicht schließende Weithalsflasche', 'nachtloesung', 'https://nalgene.eu/de/produktkategorie/nach-grose/1l-de/', 'Herstellerbeispiel · ausschließlich markiert als Urinflasche nutzen', true, 20),
  ('traveljohn', 'TravelJohn Einwegurinal', 'Gel-Urinalbeutel für den Notfall', 'nachtloesung', 'https://www.airteam.eu/de/p/traveljohn', 'Etabliertes Produktbeispiel · Preis und Bewertungen prüfen', true, 30),
  ('happypo', 'HappyPo Easy Bidet', 'Reisepo-Dusche', 'reinigung', 'https://www.dm.de/happypo-po-dusche-easy-bidet-p4260487760010.html', 'Erreichbare Händlerseite · Verfügbarkeit und Preis prüfen', true, 40),
  ('cleanwaste', 'Cleanwaste GO Anywhere', 'Falttoilette und Pack-out-System', 'packout', 'https://cleanwaste.com/product/go-anywhere-total-system/', 'Herstellerbeispiel · EU-Verfügbarkeit und Entsorgung prüfen', true, 50),
  ('thetford-335', 'Thetford Porta Potti 335', 'Kompakte Toilette mit Spülung', 'toilette', 'https://www.fritz-berger.de/artikel/thetford-porta-potti-335-tragbare-campingtoilette-116928?varid=69095', '4,9/5 aus 52 verifizierten Händlerbewertungen · Stand 10.08.2026', true, 60),
  ('boxio-toilet', 'BOXIO Toilet', 'Trockentrenntoilette im Euroboxformat', 'toilette', 'https://boxio.de/products/trenntoilette', '242 Produktbewertungen beim Hersteller · Stand 10.08.2026', true, 70),
  ('trelino-evo-s', 'Trelino Evo S', 'Kompakte Trockentrenntoilette', 'toilette', 'https://www.trelino.com/de/products/trelino%C2%AE-evo-s', 'Marke 4,7/5 bei 1.094 Trustpilot-Bewertungen · Stand 10.08.2026', true, 80),
  ('clesana-x1', 'Clesana X1', 'Mobile Verschweißtoilette', 'toilette', 'https://www.shop.clesana.com/products/clesana-x1', 'Premiumbeispiel · Preis, Akku und Verfügbarkeit prüfen', true, 90),
  ('wolfwise-privacy', 'WolfWise Privacy Tent', 'Pop-up-Sichtschutz für Toilette und Dusche', 'sichtschutz', 'https://www.wolfwise.com/products/wolfwise-pop-up-privacy-shower-tent-lp250644bl', 'Herstellerbewertungen vorhanden · Lieferbarkeit in Europa prüfen', true, 100)
on conflict (product_key) do update set
  title = excluded.title,
  recommendation = excluded.recommendation,
  category = excluded.category,
  url = excluded.url,
  rating_note = excluded.rating_note,
  sort_order = excluded.sort_order,
  updated_at = now();

insert into public.guide_sources
  (source_key, section, label, title, description, url, image_url, enabled, sort_order)
values
  ('nps-human-waste', 'sanitation', 'Praxis · National Park Service', 'Kotgrube und Pack-out', 'Vorbereitung, Abstände und WAG-Bag-Methode ↗', 'https://www.nps.gov/articles/000/idkt_lnt_3.htm', null, true, 10),
  ('cdc-norovirus', 'sanitation', 'Hygiene · CDC', 'Noroviren beim Camping vermeiden', 'Händewaschen, Toilettenbereich und sauberes Wasser ↗', 'https://www.cdc.gov/norovirus/prevention/outdoor-camping.html', null, true, 20),
  ('lnt-waste', 'sanitation', 'Umwelt · Leave No Trace', 'Abfälle richtig entsorgen', 'Urin, menschliche Ausscheidungen und sensible Gebiete ↗', 'https://lnt.org/why/7-principles/dispose-of-waste-properly/', null, true, 30),
  ('autohome-columbus-video', 'media_video', 'Überblick', 'Columbus kennenlernen', 'Form, Öffnungsprinzip und Nutzung des Hartschalen-Dachzelts im offiziellen Produktvideo.', 'https://www.youtube.com/watch?v=IzxFKFB5iTg', 'https://i.ytimg.com/vi/IzxFKFB5iTg/hqdefault.jpg', true, 10),
  ('autohome-tension-video', 'media_video', 'Abbau', 'Stoff sauber einziehen', 'Das innere elastische Spannsystem unterstützt beim geordneten Schließen der Schale.', 'https://www.youtube.com/watch?v=FRmdRz2UI3c', 'https://i.ytimg.com/vi/FRmdRz2UI3c/hqdefault.jpg', true, 20),
  ('autohome-windstop-video', 'media_video', 'Wind', 'Windstop verstehen', 'Die offizielle Funktionsdarstellung der Gasfeder-Sicherung. Bei starkem Wind abbauen.', 'https://www.youtube.com/watch?v=K-LLyqom5DM', 'https://i.ytimg.com/vi/K-LLyqom5DM/hqdefault.jpg', true, 30),
  ('columbus-manual', 'media_resource', 'PDF · Hersteller', 'Columbus Bedienungsanleitung', 'Montage, Öffnen, Schließen und modellspezifische Hinweise ↗', 'https://shop.autohome-official.com/img/cms/ISTRUZIONI/COLUMBUS/COLUMBUS_INSTRUCTIONS.pd.pdf', null, true, 10),
  ('columbus-variant', 'media_resource', 'Produkt · Hersteller', 'Columbus Variant', 'Materialien, Ausstattung und technische Angaben ↗', 'https://shop.autohome-official.com/en/columbus-range/7-columbus-variant.html', null, true, 20),
  ('autohome-compare', 'media_resource', 'Vergleich · Hersteller', 'Modelle vergleichen', 'Größen und Eigenschaften der Dachzelt-Baureihen ↗', 'https://www.autohome-official.com/en/products/comparing-all-roof-top-tents/', null, true, 30)
on conflict (source_key) do update set
  section = excluded.section,
  label = excluded.label,
  title = excluded.title,
  description = excluded.description,
  url = excluded.url,
  image_url = excluded.image_url,
  sort_order = excluded.sort_order,
  updated_at = now();

-- Erst nach der Anmeldung in admin.html ausführen und UUID ersetzen:
-- insert into public.app_admins (user_id) values ('DEINE-AUTH-USER-UUID');
